### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by scalda** [Poke1650/ModJam5#1]
#### Description:
When loading my current world i am getting the attached crash

#### What happens:

game crashes to desktop

#### What you expected to happen:

it not to crash sorry

#### How to reproduce:

not sure really it's just doing it on this world atm

#### Relevant scripts or crashlog (Please use [Gist](https://gist.github.com/), [Pastebin](https://pastebin.com/) or [Hastebin](https://hastebin.com/)):

[pastebin](https://pastebin.com/74FniLr7)
____
#### Affected Versions (Do *not* use "latest"):

- Dye it yourself:  diy-1.0.jar
- Minecraft: 1.12.2
- Forge: 14.23.2.2654

**Comment by antoinegag** [comment]
Can you go into the config (Main menu -> Mods -> Dye It Yourself -> Config -> General) and make sure that the value of  `maxDyePoop`  and `minDyePoop` are both positive (or 0) and that `maxDyePoop` is greater or equal to `minDyePoop`. 

I believe this is what is causing the issue, I forgot to add handling for that case but will do in the future.

**Comment by scalda** [comment]
ok thanks for this

**Comment by antoinegag** [comment]
This will be fixed in v1.1, uploading on CurseForge right now or you can grab it directly there: https://github.com/Poke1650/ModJam5/releases/tag/v1.1.

Thanks for the report!
